name: Check

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    container: "integritee/integritee-dev:0.1.7"
    strategy:
      fail-fast: false
      matrix:
        # We need to compile `test-no-std` separately, otherwise we have std leaks from the build-deps.
        check: [
          # exclude the packages that don't compile to std.
          cargo check --all --exclude test-no-std,
          cargo test --all --exclude test-no-std,
          cargo check -p test-no-std,
          cargo check -p test-no-std --features evm,
          cargo fmt --all -- --check,
        ]
    steps:
      - uses: actions/checkout@v2
      - name: init-rust-target
        run: rustup show

      - name: ${{ matrix.check }}
        run:  ${{ matrix.check }}



