name: Check

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    container: "integritee/integritee-dev:0.1.7"
    steps:
      - uses: actions/checkout@v2
      - name: init-rust-target
        run: rustup show

      - name: cargo test
        # exclude the packages that don't compile to std.
        run:  cargo test --all --exclude test-no-std --exclude sgx-runtime

      - name: test_no_std
        # We can only run cargo check here, as the linker will fail, as we don't have the sgx `c` files in the repo
        run: cargo check -p test-no-std

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: init-rust-target
        run: rustup show

      - name: fmt
        run:  cargo fmt --all -- --check

